version: '3'

networks:
  local_network:
    external: true

services:
  presenti:
    image: presenti
    container_name: presenti
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3004:3000
    environment:
      - TZ=Asia/Ho_Chi_Minh
    env_file:
      - .env.production
    networks:
      - local_network
