name: Build and deploy NextJS source code to Vercel
run-name: ${{ github.actor }} is building and deploying

on: workflow_dispatch

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  API_GATEWAY_URL: http://hihi.test
  SOCKET_SERVICE_URL: http://localhost:3002

jobs:
  next-build:
    name: Build and deploy NextJS source code to Vercel
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Login to Vercel
        run: vercel login --github
      - name: Build Project Artifacts
        run: vercel build
      - name: Deploy Project Artifacts to Vercel
        run: vercel --prod
