name: Presenti NextJS Deployment
run-name: ${{ github.actor }} is building and deploying automatically

on:
  # pull_request:
  #   branches:
  #     - master
  workflow_dispatch:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  build_source:
    name: Build source code
    runs-on: ubuntu-22.04
    env:
      NEXT_PUBLIC_PRESENTER_APP_URL: temp_value
      NEXT_PUBLIC_SOCKET_SERVICE_URL: temp_value
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup NodeJS environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Setup our npm registry
        run: echo "${{ secrets.NPMRC_FILE_CONTENT }}" > .npmrc

      - name: Install dependencies
        run: npm ci

      - name: Build source code
        run: npm run build --if-present

      # - name: Test source code
      #   run: npm test --if-present

  deployment:
    name: Deploy to Vercel cloud
    runs-on: ubuntu-22.04
    needs: build_source
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Setup our npm registry
        run: echo "${{ secrets.NPMRC_FILE_CONTENT }}" > .npmrc

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=${{ vars.VERCEL_ENV }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
